service: review-app-mvp-ext-database-products

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  productTable: ${self:custom.stage}-products
  backupEnabled:
    dev: false
    stage: false
    prod: true


provider:
  name: aws
  stage: dev
  region: ${opt:region,'ap-south-1'}
  profile: ${opt:profile, 'staginghta'}

resources:
  Resources:
    #Product Table Config
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.productTable}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: ${self:custom.backupEnabled.${opt:stage, self:provider.stage}}
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
          - AttributeName: lastUpdatedTime
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
          - AttributeName: lastUpdatedTime
            KeyType: RANGE  
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST


  Outputs:
    ProductTableArn:
      Value:
         Fn::GetAtt:
          - ProductTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ProductTableArn